# Server
#server.port=8080
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/veeramreddys_kitchen
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# File upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# EMAIL CONFIGURATION (FOR OTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=veeramreddyanusha9@gmail.com
spring.mail.password=chuibqpyzduwsntv

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true